"""Scripted analysis for the loop (loop-design.md, section 7).

Usage: python3 analyze.py RESULTS_DIR > RESULTS_DIR/analysis.md
"""
import json, sys, pathlib, collections, math

res = pathlib.Path(sys.argv[1])
CODES = ["PV", "PE", "RD", "AO", "OT"]


def comb2(n):
    return n * (n - 1) / 2


def ari(a, b):
    """Adjusted Rand index between two labelings (dicts id -> label) on shared ids."""
    ids = sorted(set(a) & set(b))
    n = len(ids)
    if n < 2:
        return float("nan")
    cont = collections.Counter((a[i], b[i]) for i in ids)
    ra = collections.Counter(a[i] for i in ids)
    rb = collections.Counter(b[i] for i in ids)
    s = sum(comb2(v) for v in cont.values())
    sa = sum(comb2(v) for v in ra.values())
    sb = sum(comb2(v) for v in rb.values())
    exp = sa * sb / comb2(n)
    mx = (sa + sb) / 2
    return (s - exp) / (mx - exp) if mx != exp else 1.0


def kappa(a, b):
    ids = sorted(set(a) & set(b))
    n = len(ids)
    po = sum(a[i] == b[i] for i in ids) / n
    ca, cb = collections.Counter(a[i] for i in ids), collections.Counter(b[i] for i in ids)
    pe = sum(ca[c] * cb[c] for c in CODES) / n / n
    return (po - pe) / (1 - pe), po, n


def load_codes(name):
    out = {}
    for line in (res / "codes" / f"{name}.jsonl").read_text().splitlines():
        if line.strip():
            r = json.loads(line)
            out[r["id"]] = r["primary"]
    return out


def load_clusters(k):
    d = json.loads((res / "clusters" / f"iter-{k}.json").read_text())
    lab, meta = {}, {}
    for c in d["clusters"]:
        meta[c["cluster_id"]] = c
        for i in c["record_ids"]:
            lab[i] = c["cluster_id"]
    for i in d.get("unclustered", []):
        lab[i] = "U:" + i  # each unclustered record is its own singleton
    return lab, meta, d


print("# Loop analysis (scripted)\n")
print("Generated by `loop-tools/analyze.py`. Interpretation rules: `loop-design.md`, section 7.\n")

# Coder agreement
A, B = load_codes("coder-A"), load_codes("coder-B")
k, po, n = kappa(A, B)
print("## Coder agreement\n")
print(f"Records coded by both: {n}. Raw agreement {po:.2f}. Cohen's kappa **{k:.2f}**"
      f" ({'meets' if k >= 0.6 else 'below'} the 0.6 threshold).\n")
print("| Code | Coder A | Coder B | Both (agreed) |\n| --- | --- | --- | --- |")
agreed = {i: A[i] for i in A if B.get(i) == A[i]}
for c in CODES:
    print(f"| {c} | {sum(v == c for v in A.values())} | {sum(v == c for v in B.values())} | "
          f"{sum(v == c for v in agreed.values())} |")
print()
dis = collections.Counter((A[i], B[i]) for i in A if i in B and A[i] != B[i])
print("Disagreements (A → B): " + ", ".join(f"{a}→{b}: {v}" for (a, b), v in dis.most_common()) + "\n")

# Stability
print("## Stability across iterations\n")
labs = {}
for it in range(1, 6):
    labs[it], _, _ = load_clusters(it)
print("| Transition | Shared records | Adjusted Rand index |\n| --- | --- | --- |")
for it in range(1, 5):
    shared = len(set(labs[it]) & set(labs[it + 1]))
    print(f"| {it}→{it+1} | {shared} | {ari(labs[it], labs[it+1]):.2f} |")
s34, s45 = ari(labs[3], labs[4]), ari(labs[4], labs[5])
print(f"\nStable (both 3→4 and 4→5 ≥ 0.6): **{'yes' if s34 >= 0.6 and s45 >= 0.6 else 'no'}**.\n")


def where(codes, it, label):
    lab, meta, _ = load_clusters(it)
    recs = [i for i, c in codes.items() if c == label and i in lab]
    cnt = collections.Counter(lab[i] for i in recs)
    return len(recs), cnt, meta


def describe(codes, title):
    print(f"## Where coded activities fall ({title})\n")
    final = {}
    for label in ["PV", "PE", "RD", "AO"]:
        print(f"### {label}\n")
        print("| Iteration | Records | Top cluster | Share | Second | Share |\n| --- | --- | --- | --- | --- | --- |")
        hits = 0
        eligible = 0
        for it in range(1, 6):
            n, cnt, meta = where(codes, it, label)
            if n == 0:
                print(f"| {it} | 0 | — | — | — | — |")
                continue
            top = cnt.most_common(2)
            def name(c):
                return c if c.startswith("U:") else f"{c}: {meta[c]['description'][:60]}"
            t1 = top[0]
            t2 = top[1] if len(top) > 1 else ("—", 0)
            print(f"| {it} | {n} | {name(t1[0])} | {t1[1]/n:.0%} | "
                  f"{name(t2[0]) if t2[0] != '—' else '—'} | {t2[1]/n:.0%} |")
            if n >= 10:
                eligible += 1
                hits += t1[1] / n >= 0.6
            if it == 5:
                final[label] = (n, cnt, meta)
        print(f"\nIterations with ≥10 records: {eligible}; of those with ≥60% in one cluster: {hits}.\n")
    return final


def verdicts(final):
    print("### Verdicts under the pre-registered rules\n")
    for label in ["PV", "PE", "RD", "AO"]:
        if label not in final:
            print(f"- {label}: no records in the final iteration.")
            continue
        n, cnt, meta = final[label]
        top, v = cnt.most_common(1)[0]
        share = v / n
        status = ("clusters together" if share >= 0.6 else "dispersed" if share <= 0.4 else "partly concentrated")
        roles = meta[top]["roles"] if top in meta else []
        exists = [r.get("exists_today") for r in roles]
        kind = ("absorbed (existing role)" if exists and all(exists) else
                "distinct candidate (no stable title)" if exists and not any(exists) else "mixed")
        print(f"- **{label}**: {n} records; top cluster {top} holds {share:.0%} → {status}; "
              f"that cluster is attributed to: {kind} — "
              + "; ".join(f"{r.get('role')} ({'exists: ' + str(r.get('existing_title')) if r.get('exists_today') else 'new'})" for r in roles))
    if "PV" in final and "PE" in final:
        npv, cpv, _ = final["PV"]
        npe, cpe, _ = final["PE"]
        co = [c for c in set(cpv) & set(cpe) if cpv[c] / npv >= 0.4 and cpe[c] / npe >= 0.4]
        print(f"- **PV and PE co-cluster** (each ≥40% in the same cluster): {'yes: ' + ', '.join(co) if co else 'no'}")
    print()


final = describe(agreed, "codes both coders agreed on")
verdicts(final)
print("## Sensitivity: coder A only\n")
verdicts(describe(A, "coder A") or {})
print("## Sensitivity: coder B only\n")
verdicts(describe(B, "coder B") or {})

# Final clusters summary
_, meta, d = load_clusters(5)
print("## Final clusters (iteration 5)\n")
print("| Cluster | Records | Description | Roles (exists today?) |\n| --- | --- | --- | --- |")
for cid, c in meta.items():
    roles = "; ".join(f"{r.get('role')} ({'yes: ' + str(r.get('existing_title')) if r.get('exists_today') else 'no'})" for r in c["roles"])
    print(f"| {cid} | {len(c['record_ids'])} | {c['description']} | {roles} |")
print(f"\nUnclustered: {len(d.get('unclustered', []))}\n")
