"""Weighted industry scores and scorer agreement (industry-analogue-design.md, section 3).

Usage: python3 score_industries.py RESULTS_DIR > RESULTS_DIR/scoring.md
"""
import json, sys, pathlib

W = {"D1": 3, "D2": 2, "D3": 3, "D4": 2, "D5": 2, "D6": 1, "D7": 1, "D8": 2}
res = pathlib.Path(sys.argv[1])
A = json.loads((res / "scores-A.json").read_text())
B = json.loads((res / "scores-B.json").read_text())


def total(s):
    return sum(W[d] * s[d]["score"] for d in W)


inds = sorted(A)
ta = {i: total(A[i]) for i in inds}
tb = {i: total(B[i]) for i in inds}
mean = {i: (ta[i] + tb[i]) / 2 for i in inds}
order = sorted(inds, key=lambda i: -mean[i])


def ranks(t):
    s = sorted(inds, key=lambda i: -t[i])
    return {i: s.index(i) + 1 for i in inds}


ra, rb = ranks(ta), ranks(tb)
n = len(inds)
rho = 1 - 6 * sum((ra[i] - rb[i]) ** 2 for i in inds) / (n * (n * n - 1))
cells = [(A[i][d]["score"], B[i][d]["score"]) for i in inds for d in W]
exact = sum(a == b for a, b in cells) / len(cells)
within1 = sum(abs(a - b) <= 1 for a, b in cells) / len(cells)

print("# Industry scoring\n")
print("Generated by `loop-tools/score_industries.py`. Weights and decision rule: `industry-analogue-design.md`, section 3. Maximum 64.\n")
print("| Rank | Industry | Scorer A | Scorer B | Mean | " + " | ".join(W) + " |")
print("| --- | --- | --- | --- | --- | " + " | ".join("---" for _ in W) + " |")
for k, i in enumerate(order, 1):
    dims = " | ".join(f"{A[i][d]['score']}/{B[i][d]['score']}" for d in W)
    print(f"| {k} | {i} | {ta[i]} | {tb[i]} | {mean[i]:.1f} | {dims} |")
print(f"\nDimension cells show scorer A / scorer B. Weights: " + ", ".join(f"{d}×{w}" for d, w in W.items()) + ".\n")
print(f"Agreement: Spearman rank correlation of totals **{rho:.2f}**; identical cell scores {exact:.0%}; within one point {within1:.0%}.\n")
topA, topB = max(inds, key=lambda i: ta[i]), max(inds, key=lambda i: tb[i])
gap = abs(ta[topA] - ta[topB]) if topA != topB else 0
gapB = abs(tb[topA] - tb[topB]) if topA != topB else 0
print("## Decision\n")
if topA != topB and max(gap, gapB) > 6:
    print(f"Scorers disagree on the top industry ({topA} vs {topB}) by more than 6 points: both are co-primary.")
else:
    print(f"Primary analogue: **{order[0]}** (mean {mean[order[0]]:.1f}). Runner-up: **{order[1]}** (mean {mean[order[1]]:.1f}).")
    if topA != topB:
        print(f"\nScorers' top choices differ ({topA} vs {topB}) but within 6 points, so the mean decides.")
