#!/usr/bin/env python3
"""Load a sign-up export (CSV from export.sh) into this Worker's KV namespace.

Use it to move the member list to a new deployment, e.g. after running setup.sh on
another Cloudflare account:

  ./export.sh old.csv                      # against the OLD worker (old config.json)
  python3 import.py old.csv --dry-run      # check what would be written
  python3 import.py old.csv                # write to the namespace in wrangler.jsonc

Roles, original signup dates, and sources are kept. Unsubscribe links are not imported:
they are signed per deployment and regenerated by the new Worker's export.
The member list is personal data: keep CSVs out of the repo (signups-*.csv is gitignored).
"""
import csv, json, re, subprocess, sys, tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
FIELDS = ["name", "email", "affiliation", "website", "github", "discord", "role"]

def namespace_id():
    s = (HERE / "wrangler.jsonc").read_text()
    m = re.search(r'"binding": "SIGNUPS", "id": "([0-9a-f]{32})"', s)
    if not m:
        sys.exit("Could not find the SIGNUPS namespace id in wrangler.jsonc")
    return m.group(1)

def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    dry = "--dry-run" in sys.argv
    if len(args) != 1:
        sys.exit(__doc__)
    rows = []
    with open(args[0], newline="") as f:
        for r in csv.DictReader(f):
            email = (r.get("email") or "").strip().lower()
            if not re.match(r"^[^\s@]+@[^\s@]+\.[^\s@]+$", email):
                print(f"skipping row without a valid email: {r.get('name', '')!r}")
                continue
            rec = {k: (r.get(k) or "").strip() for k in FIELDS}
            rec["email"] = email
            rec["role"] = rec["role"] or "member"
            rec["ts"] = (r.get("signed_up") or "").strip()
            rec["source"] = (r.get("source") or "import").strip()
            if (r.get("updated") or "").strip():
                rec["updated"] = r["updated"].strip()
            rows.append({"key": f"sub:{email}", "value": json.dumps(rec, ensure_ascii=False)})
    roles = {}
    for r in rows:
        role = json.loads(r["value"])["role"]
        roles[role] = roles.get(role, 0) + 1
    print(f"{len(rows)} sign-ups ready: {roles}")
    if dry:
        print("dry run: nothing written")
        return
    with tempfile.TemporaryDirectory() as tmp:
        bulk = Path(tmp) / "bulk.json"
        bulk.write_text(json.dumps(rows, ensure_ascii=False))
        subprocess.run(["npx", "wrangler", "kv", "bulk", "put", str(bulk),
                        "--namespace-id", namespace_id(), "--remote"], cwd=HERE, check=True)
    print("imported. Check with ./export.sh")

if __name__ == "__main__":
    main()
