#!/usr/bin/env python3
"""Generate a site design from a seed: assets/seed.css plus assets/seed.json (fonts and choices).

Every choice is drawn from lists of options that all say "hard, technical, engineered", so any seed
gives a coherent design and the same seed always gives the same design.
Usage: python3 tools/design_seed.py [SEED]   (no seed: draw one)
"""
import json, random, secrets, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

TYPE = [  # (sans, mono, google families)
    ("Space Grotesk", "JetBrains Mono", "Space+Grotesk:wght@400;500;700&family=JetBrains+Mono:wght@400;600"),
    ("Inter Tight", "IBM Plex Mono", "Inter+Tight:wght@400;500;700&family=IBM+Plex+Mono:wght@400;500"),
    ("Archivo", "Fragment Mono", "Archivo:wght@400;500;700;800&family=Fragment+Mono"),
    ("Schibsted Grotesk", "DM Mono", "Schibsted+Grotesk:wght@400;500;700&family=DM+Mono:wght@400;500"),
    ("Instrument Sans", "Martian Mono", "Instrument+Sans:wght@400;500;700&family=Martian+Mono:wght@400;500"),
    ("Bricolage Grotesque", "Geist Mono", "Bricolage+Grotesque:wght@400;600;800&family=Geist+Mono:wght@400;500"),
    ("Sora", "Red Hat Mono", "Sora:wght@400;600;700&family=Red+Hat+Mono:wght@400;500"),
    ("Chivo", "Chivo Mono", "Chivo:wght@400;500;700;800&family=Chivo+Mono:wght@400;500"),
]
PALETTES = {  # bg, fg, muted, rule, fill, accent, accent-ink (text on accent), dark?
    "blueprint":      ("#0d2b4e", "#e9f1fb", "#9fb8d6", "#2c5282", "#123763", "#ffd23f", "#0d2b4e", True),
    "safety orange":  ("#f4f2ec", "#161616", "#62615c", "#cfccc3", "#e9e6dd", "#ff5a1f", "#161616", False),
    "terminal":       ("#0a0d0a", "#d7f5d7", "#7fa37f", "#1f3a1f", "#101810", "#39ff6a", "#0a0d0a", True),
    "graphite signal":("#e6e6e3", "#1b1c1e", "#5b5d61", "#b9bab6", "#d9d9d5", "#e5202e", "#ffffff", False),
    "steel cobalt":   ("#f7f8fa", "#0e1116", "#5a6270", "#d3d8e0", "#eceff4", "#004fcc", "#ffffff", False),
    "amber crt":      ("#140e05", "#ffcf7a", "#b48a45", "#3a2a10", "#1c1408", "#ff9d00", "#140e05", True),
    "lab white":      ("#ffffff", "#0b0b0b", "#6d6d6d", "#e2e2e2", "#f4f4f4", "#00a37a", "#ffffff", False),
    "hazard":         ("#fdf8e1", "#111111", "#595544", "#d9d0a8", "#f5edc4", "#111111", "#ffd400", False),
}
MOTIFS = ["dot grid", "line grid", "ruler margin", "hatched bands", "crosshairs", "scanlines", "none"]
LAYOUTS = ["narrow column", "left rail", "wide spec"]
HEADINGS = ["section sign", "bracket index", "mono kicker", "hash", "inverted bar"]
RULES = ["hairline", "heavy", "double", "dashed"]
BUTTONS = ["solid slab", "offset shadow", "outline", "hatched"]
LINKS = ["underline", "boxed", "arrow", "highlight"]
DENSITY = ["compact", "regular", "airy"]


def generate(seed):
    r = random.Random(seed)
    sans, mono, fam = r.choice(TYPE)
    pname = r.choice(sorted(PALETTES)); bg, fg, muted, rule, fill, acc, accink, dark = PALETTES[pname]
    c = {"seed": seed, "type": [sans, mono], "palette": pname, "motif": r.choice(MOTIFS), "layout": r.choice(LAYOUTS),
         "heading": r.choice(HEADINGS), "rule": r.choice(RULES), "button": r.choice(BUTTONS), "link": r.choice(LINKS),
         "density": r.choice(DENSITY), "caps_nav": r.random() < .6, "body_mono": r.random() < .18,
         "h1_size": round(r.uniform(2.0, 3.6), 2), "tracking": round(r.uniform(-.035, .01), 3)}
    lw = {"hairline": "1px solid", "heavy": "3px solid", "double": "4px double", "dashed": "1px dashed"}[c["rule"]]
    lead = {"compact": 1.5, "regular": 1.62, "airy": 1.75}[c["density"]]
    gap = {"compact": 2.2, "regular": 3, "airy": 4}[c["density"]]
    body_font = "var(--mono)" if c["body_mono"] else "var(--sans)"
    width = {"narrow column": "40rem", "left rail": "56rem", "wide spec": "52rem"}[c["layout"]]
    css = [f"""/* Generated by tools/design_seed.py · seed {seed} · {pname} · {sans} + {mono} · {c['motif']} · {c['layout']}
   · headings: {c['heading']} · rules: {c['rule']} · buttons: {c['button']} · links: {c['link']} · {c['density']} */
:root {{ color-scheme: {'dark' if dark else 'light'};
  --bg: {bg}; --fg: {fg}; --muted: {muted}; --rule: {rule}; --fill: {fill}; --link: {acc if pname != 'hazard' else fg}; --link-hover: {fg};
  --acc: {acc}; --acc-ink: {accink}; --sans: "{sans}", system-ui, sans-serif; --mono: "{mono}", ui-monospace, Menlo, monospace; --line: {lw} var(--fg); }}
html {{ background: var(--bg); }}
body {{ max-width: {width}; background-color: var(--bg); color: var(--fg); font: 1rem/{lead} {body_font}; }}
.btn, a.btn, .register button[type=submit], .btn-quiet, a.btn-quiet, .register input, .map-filters button, .prompt pre {{ font-family: var(--sans); }}
code, .prompt pre {{ font-family: var(--mono); }}
::selection {{ background: var(--acc); color: var(--acc-ink); }}
:focus-visible {{ outline: 2px solid var(--acc); outline-offset: 2px; border-radius: 0; }}
h1, h2, h3 {{ font-family: var(--sans); letter-spacing: {c['tracking']}em; }}
h1 {{ font-size: {c['h1_size']}rem; line-height: 1.02; font-weight: 700; }}
h2 {{ margin-top: {gap}rem; }}
.meta, .small, .kind, .status, .rows .k, .docmeta, footer {{ font-family: var(--mono); }}
.meta, .small, .kind {{ font-size: .8rem; }}
.status {{ font-style: normal; text-transform: uppercase; letter-spacing: .06em; }}
header {{ border-bottom: var(--line); padding-bottom: .9rem; margin-bottom: 0; }}
header .home {{ color: var(--fg); }} header .logo {{ border-radius: 0; }}
header nav a {{ color: var(--muted); {'text-transform: uppercase; letter-spacing: .08em; font: 500 .78rem var(--mono);' if c['caps_nav'] else ''} }}
header nav a[aria-current] {{ color: var(--fg); text-decoration: none; box-shadow: inset 0 -3px 0 var(--acc); }}
.docmeta {{ display: flex; flex-wrap: wrap; gap: .4rem 1.2rem; margin: 0 0 {gap}rem; padding: .55rem 0; border-bottom: 1px solid var(--rule); font-size: .72rem; letter-spacing: .05em; text-transform: uppercase; color: var(--muted); }}
.docmeta span:first-child {{ color: var(--fg); }}
.docmeta .seed {{ color: var(--acc); }}
footer {{ border-top: var(--line); font-size: .78rem; }}
blockquote {{ border-left: 3px solid var(--acc); color: var(--fg); }}
.lede {{ font-size: 1.15rem; }}
"""]
    # motif
    m = c["motif"]
    if m == "dot grid":
        css.append(f"body {{ background-image: radial-gradient(color-mix(in srgb, var(--fg) 16%, transparent) 1px, transparent 1.2px); background-size: 18px 18px; }}")
    elif m == "line grid":
        css.append("body { background-image: linear-gradient(color-mix(in srgb, var(--fg) 6%, transparent) 1px, transparent 1px), linear-gradient(90deg, color-mix(in srgb, var(--fg) 6%, transparent) 1px, transparent 1px); background-size: 32px 32px; }")
    elif m == "ruler margin":
        css.append("html { background-image: repeating-linear-gradient(var(--fg) 0 1px, transparent 1px 8px), repeating-linear-gradient(var(--fg) 0 1px, transparent 1px 40px); background-size: 8px 100%, 16px 100%; background-repeat: repeat-y; background-position: 0 0, 0 0; } body { background: transparent; }")
    elif m == "hatched bands":
        css.append("header { border-bottom: 0; } header::after { content: \"\"; flex-basis: 100%; height: 10px; margin-top: .6rem; background: repeating-linear-gradient(-45deg, var(--fg) 0 2px, transparent 2px 7px); } footer { border-top: 0; } footer::before { content: \"\"; display: block; height: 10px; margin-bottom: 1rem; background: repeating-linear-gradient(-45deg, var(--fg) 0 2px, transparent 2px 7px); }")
    elif m == "crosshairs":
        css.append("body { background-image: linear-gradient(var(--fg), var(--fg)), linear-gradient(var(--fg), var(--fg)); background-size: 11px 1px, 1px 11px; background-position: 5px 10px, 10px 5px; background-repeat: no-repeat; } main > h2 { position: relative; } main > h2::after { content: \"+\"; position: absolute; left: -1.4rem; top: .2rem; font: 400 1rem var(--mono); color: var(--acc); }")
    elif m == "scanlines":
        css.append("body::before { content: \"\"; position: fixed; inset: 0; pointer-events: none; z-index: 99; background: repeating-linear-gradient(transparent 0 2px, color-mix(in srgb, var(--fg) 5%, transparent) 2px 3px); }")
    # layout
    if c["layout"] == "left rail":
        # headings float into a left rail; everything else runs in the right column; the page top stays full width
        css.append("@media (min-width: 60rem) { main { padding-left: 14rem; } main > h1, main > .lede, main > .next, main > .meta, main > .page-nav, main > .map-wrap { margin-left: -14rem; } main > h2 { float: left; clear: both; width: 12.5rem; margin: 0 0 0 -14rem; } main > h2 + * { margin-top: 0; } main > h2 ~ * { clear: none; } main > :is(p, ul, ol, div, details, section) { margin-top: 0; } main > h2 { margin-top: 3rem; } main > h2 + *:not(.never) { padding-top: 3rem; } }")
    elif c["layout"] == "wide spec":
        css.append("main > p, main > ul, main > ol:not(.plan) { max-width: 40rem; } .rows li { grid-template-columns: 11rem 1fr; }")
    # headings
    h = c["heading"]
    css.append("main { counter-reset: sec; } main > h2 { counter-increment: sec; }")
    if h == "section sign":
        css.append("main > h2::before { content: \"§\" counter(sec) \" \"; font-family: var(--mono); color: var(--acc); margin-right: .5rem; }")
    elif h == "bracket index":
        css.append("main > h2::before { content: \"[\" counter(sec, decimal-leading-zero) \"]\"; font: 500 .8em var(--mono); color: var(--muted); margin-right: .7rem; }")
    elif h == "mono kicker":
        css.append("main > h2 { padding-top: 1.1rem; border-top: var(--line); } main > h2::before { content: \"SECTION \" counter(sec, decimal-leading-zero); display: block; margin-bottom: .35rem; font: 500 .7rem var(--mono); letter-spacing: .14em; color: var(--acc); }")
    elif h == "hash":
        css.append("main > h2::before { content: \"#\"; font-family: var(--mono); color: var(--acc); margin-right: .45rem; }")
    elif h == "inverted bar":
        css.append("main > h2 { display: inline-block; padding: .25rem .6rem; background: var(--fg); color: var(--bg); font-size: 1.05rem; text-transform: uppercase; letter-spacing: .06em; } main > h2::before { content: counter(sec, decimal-leading-zero) \" / \"; font-family: var(--mono); color: var(--acc); }")
    # rules everywhere lists and rows appear
    css.append(".rows li, .people > div, .card, ol.plan > li, .schedule li { border-top: 1px solid var(--rule); }")
    css.append(".rows li:first-child, .people > div:first-child, .card:first-child, ol.plan > li:first-child { border-top: var(--line); }")
    css.append(".rows li:last-child, .people > div:last-child, .card:last-child, ol.plan > li:last-child { border-bottom: var(--line); }")
    css.append(".rows .k { text-transform: uppercase; letter-spacing: .08em; font-size: .72rem; color: var(--fg); }")
    css.append("ol.plan h3 .n { font-family: var(--mono); color: var(--acc); } .card .status { color: var(--acc); }")
    # the next-session box
    css.append(".next, .prompt { border-radius: 0; background: var(--fill); border: var(--line); }")
    css.append(".next .kind { text-transform: uppercase; letter-spacing: .1em; font-size: .72rem; color: var(--acc); } .next .when { font-family: var(--mono); font-size: .82rem; }")
    css.append(".next .what a { color: var(--fg); }")
    # buttons
    b = c["button"]
    base = ".btn, a.btn, .register button[type=submit]"
    if b == "solid slab":
        css.append(f"{base} {{ border-radius: 0; background: var(--acc); color: var(--acc-ink); font-weight: 700; text-transform: uppercase; letter-spacing: .06em; }} .btn:hover, a.btn:hover {{ background: var(--fg); color: var(--bg); }}")
    elif b == "offset shadow":
        css.append(f"{base} {{ border-radius: 0; background: var(--fg); color: var(--bg); box-shadow: 4px 4px 0 var(--acc); }} .btn:hover, a.btn:hover {{ background: var(--fg); color: var(--bg); transform: translate(-1px,-1px); box-shadow: 5px 5px 0 var(--acc); }} .btn:active {{ transform: translate(4px,4px); box-shadow: none; }}")
    elif b == "outline":
        css.append(f"{base} {{ border-radius: 0; background: transparent; color: var(--fg); border: 2px solid var(--fg); font-family: var(--mono); text-transform: uppercase; letter-spacing: .08em; }} .btn:hover, a.btn:hover {{ background: var(--acc); color: var(--acc-ink); border-color: var(--acc); }}")
    else:
        css.append(f"{base} {{ border-radius: 0; color: var(--acc-ink); background: repeating-linear-gradient(-45deg, var(--acc) 0 6px, color-mix(in srgb, var(--acc) 80%, var(--fg)) 6px 12px); border: 2px solid var(--fg); font-weight: 700; text-transform: uppercase; }} .btn:hover, a.btn:hover {{ background: var(--fg); color: var(--bg); }}")
    # links
    l = c["link"]
    if l == "underline":
        css.append("main a { text-decoration-thickness: 2px; text-underline-offset: .2em; }")
    elif l == "boxed":
        css.append("main p a:not(.more-ic), main li a { text-decoration: none; padding: 0 .2em; border: 1px solid color-mix(in srgb, var(--link) 50%, transparent); } main p a:hover, main li a:hover { background: var(--link); color: var(--bg); }")
    elif l == "arrow":
        css.append("main p a:not(.more-ic):not(.quiet)::after { content: \"↗\"; font-family: var(--mono); font-size: .8em; margin-left: .1em; } main a { text-decoration-thickness: 1px; }")
    else:
        css.append("main p a:not(.more-ic), main li a { text-decoration: none; background: linear-gradient(transparent 60%, color-mix(in srgb, var(--acc) 40%, transparent) 60%); color: var(--fg); } main p a:hover, main li a:hover { background: var(--acc); color: var(--acc-ink); }")
    css.append("a.quiet, .meta a, .muted a, footer p a { color: inherit; }")
    # dialog, map, misc
    css.append(".register { border-radius: 0; background: var(--bg); color: var(--fg); border: var(--line); } .register input { border-radius: 0; background: var(--bg); color: var(--fg); border-color: var(--fg); } .register .close { border-radius: 0; }")
    css.append(".map-wrap { border: var(--line); background: #fff; } .map-zoom button, .map-tip { border-radius: 0; } svg.map text { font-family: var(--sans); } svg.map text.area, svg.map .tag text { font-family: var(--mono); }")
    if dark:
        css.append(".map-wrap { background: #fff; color: #111; } .map-info { color: var(--fg); }")
    css.append(".more-ic { color: var(--acc); }")
    (ROOT / "assets/seed.css").write_text("\n".join(css) + "\n")
    c["fonts"] = fam
    (ROOT / "assets/seed.json").write_text(json.dumps(c, indent=1))
    return c


if __name__ == "__main__":
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else secrets.randbits(32)
    print(json.dumps({k: v for k, v in generate(seed).items() if k != "fonts"}, indent=1))
